name: pokedex
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: 9.1.1
  dio: ^5.9.0
  flutter_dotenv: ^6.0.0
  flutter_modular: ^6.4.1
  result_dart: ^2.1.1
  flutter_svg: ^2.2.2
  shared_preferences: ^2.5.3
  connectivity_plus: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  bloc_test: ^10.0.0
  mocktail: ^1.0.4
  flutter_native_splash: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - pokedex.env
    - assets/svg/
    - assets/png/
    - assets/fonts/
    - assets/png/pokedex.png

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Black.ttf
        - asset: assets/fonts/Roboto/Roboto-Italic.ttf
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto/Roboto-ExtraBold.ttf
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
        - asset: assets/fonts/Roboto/Roboto-Thin.ttf

